# ----------------------------------------------------------------

FROM node:24-slim AS builder

ENV NODE_TLS_REJECT_UNAUTHORIZED=0

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN corepack enable && \
    corepack prepare pnpm@11.25.0 --activate && \
    pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

# ----------------------------------------------------------------

FROM nginx:1.31.6-alpine AS final

USER root

RUN rm -rf /usr/share/nginx/html/*

WORKDIR /usr/share/nginx/html

COPY docker/stage/nginx.conf /etc/nginx/conf.d/default.conf
COPY public/index.html .
COPY --from=builder /app/dist/ ./assets/

RUN chown -R nginx:nginx /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx","-g","daemon off;"]
